package u6pp;

public class UnoFrontend {
    //coding yes yes yes

//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND

//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND

//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND//LOSE MY MIND
    //LOSE MY MIND
}
